# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('age', models.IntegerField(default=-1)),
                ('gender', models.CharField(choices=[('Masculino', 'Femenino')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SongClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_label', models.CharField(max_length=300)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='classifications',
            field=models.ManyToManyField(to='music.SongClassification'),
        ),
    ]
