# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(default=15),
        ),
    ]
