# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 05:25
from __future__ import unicode_literals

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20161214_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='songs'),
        ),
    ]
