# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20170122_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='has_hearing_problem',
            field=models.BooleanField(default=False, verbose_name='Posee impedimentos Auditivos'),
        ),
        migrations.AddField(
            model_name='participant',
            name='has_physical_problem',
            field=models.BooleanField(default=False, verbose_name='Posee impedimentos f\xedsicos'),
        ),
        migrations.AddField(
            model_name='participant',
            name='hearing_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='knows_music_theory',
            field=models.BooleanField(default=False, verbose_name='Posee concoimientos de teor\xeda musical/armon\xeda b\xe1sica'),
        ),
        migrations.AddField(
            model_name='participant',
            name='physical_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='scolarity',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default=('Ninguno', 'Ninguno'), max_length=50),
        ),
    ]
