# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20170125_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_uvg',
            field=models.BooleanField(default=False),
        ),
    ]
