# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-26 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_participant_is_uvg'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cloud_front_path',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
