# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_song_cloud_front_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='has_psychological_problem',
            field=models.BooleanField(default=False, verbose_name='Posee alg\xfan problema o desorden psicol\xf3gico'),
        ),
        migrations.AddField(
            model_name='participant',
            name='psychological_problem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
