# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20170128_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='songclassification',
            name='date_taken',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_hearing_problem',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default=('Si', 'Si'), max_length=50, verbose_name='Posee impedimentos Auditivos'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_physical_problem',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default=('Si', 'Si'), max_length=50, verbose_name='Posee impedimentos f\xedsicos'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='has_psychological_problem',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default=('Si', 'Si'), max_length=50, verbose_name='Posee alg\xfan problema o desorden psicol\xf3gico'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='knows_music_theory',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default=('Si', 'Si'), max_length=50, verbose_name='Posee concoimientos de teor\xeda musical/armon\xeda b\xe1sica'),
        ),
    ]
