# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20170128_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='songclassification',
            name='time_taken',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
