# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_songclassification_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='scolarity',
            field=models.CharField(choices=[('Ninguno', 'Ninguno'), ('Primaria', 'Primaria'), ('Basicos', 'Basicos'), ('Bachillerato', 'Bachillerato'), ('Universitario', 'Universitario'), ('Licenciatura', 'Licenciatura'), ('Maestr\xedas/Doctorados', 'Maestr\xedas/Doctorados')], default=('Ninguno', 'Ninguno'), max_length=50),
        ),
    ]
