# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-09 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_auto_20170131_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='mood',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
